<?xml version="1.0" encoding="UTF-8" ?>
<!-- SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government -->
<!-- SPDX-License-Identifier: EUPL-1.2 -->
<project
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
>
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>4.1.1</version>
    <relativePath />
  </parent>

  <groupId>se.digg.wallet</groupId>
  <artifactId>wallet-client-gateway-ci-test</artifactId>
  <version>0.0.5</version>
  <packaging>jar</packaging>

  <name>Wallet Client Gateway CI Test</name>
  <description>CI test copy of the European Digital Identity Wallet Client Gateway</description>
  <url>https://github.com/diggsweden/wallet-client-gateway-ci-test</url>
  <organization>
    <name>Digg - Agency for Digital Government</name>
    <url>https://www.digg.se</url>
  </organization>
  <licenses>
    <license>
      <name>EUPL License</name>
      <url>https://opensource.org/license/eupl-1-2</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <organization>Digg - Agency for Digital Government</organization>
      <organizationUrl>https://www.digg.se</organizationUrl>
    </developer>
  </developers>

  <scm>
    <connection>
      scm:git:https://github.com/diggsweden/wallet-client-gateway-ci-test.git
    </connection>
    <developerConnection>
      scm:git:https://github.com/diggsweden/wallet-client-gateway-ci-test.git
    </developerConnection>
    <url>https://github.com/diggsweden/wallet-client-gateway-ci-test</url>
  </scm>
  <issueManagement>
    <system>GitHub</system>
    <url>https://github.com/diggsweden/wallet-client-gateway-ci-test/issues</url>
  </issueManagement>

  <properties>
    <java.version>25</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    
    <formatter-maven-plugin.version>2.29.0</formatter-maven-plugin.version>
    <maven-checkstyle-plugin.version>3.6.0</maven-checkstyle-plugin.version>
    <checkstyle.version>13.11.0</checkstyle.version>
    <maven-pmd-plugin.version>3.28.0</maven-pmd-plugin.version>
    <spotbugs-maven-plugin.version>4.10.4.1</spotbugs-maven-plugin.version>
    <record-builder.version>52</record-builder.version>
    <openapi-generator-maven-plugin.version>7.25.0</openapi-generator-maven-plugin.version>
    <build-helper-maven-plugin.version>3.6.2</build-helper-maven-plugin.version>
    <openapi-diff-maven.version>2.1.7</openapi-diff-maven.version>
    <jacoco-maven-plugin.version>0.8.15</jacoco-maven-plugin.version>


    <wallet-account-spec.repo>diggsweden/wallet-account</wallet-account-spec.repo>
    <wallet-account-spec.ref>78f7591424f8dc17e320dec9c8764514e865da19</wallet-account-spec.ref>
    <wallet-account-spec.path>src/main/resources/static/wallet-account-openapi-v0.yaml</wallet-account-spec.path>
    <wallet-account-origin-spec.path>src/main/resources/static/wallet-account-openapi-origin.yaml</wallet-account-origin-spec.path>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webmvc</artifactId>
    </dependency>
    <dependency>
      <!-- Temporary added due to vulnerability issue with version 11.0.21
      embedded in spring-boot-starter-parent 4.0.6 -->
      <groupId>org.apache.tomcat.embed</groupId>
      <artifactId>tomcat-embed-core</artifactId>
      <version>11.0.26</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-session-data-redis</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <version>3.1.1</version>
    </dependency>
    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>jackson-databind-nullable</artifactId>
      <version>0.2.11</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jdk8</artifactId>
      <version>2.22.2</version>
    </dependency>
    <dependency>
      <groupId>com.nimbusds</groupId>
      <artifactId>nimbus-jose-jwt</artifactId>
      <version>10.10</version>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-tracing-bridge-brave</artifactId>
    </dependency>
    <dependency>
      <groupId>io.soabase.record-builder</groupId>
      <artifactId>record-builder-core</artifactId>
      <version>${record-builder.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-prometheus</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <optional>true</optional>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-testcontainers</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webmvc-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.wiremock.integrations</groupId>
      <artifactId>wiremock-spring-boot</artifactId>
      <version>4.4.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
      <version>1.21.4</version>
    </dependency>
    <dependency>
      <groupId>com.redis</groupId>
      <artifactId>testcontainers-redis</artifactId>
      <version>2.2.4</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>3.27.7</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.awaitility</groupId>
      <artifactId>awaitility</artifactId>
      <version>4.3.0</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>dev</id>
      <activation>
        <property>
          <name>env</name>
          <value>dev</value>
        </property>
      </activation>
      <dependencies>
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-docker-compose</artifactId>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>update-account-spec</id>
      <build>
        <plugins>
          <plugin>
            <groupId>com.googlecode.maven-download-plugin</groupId>
            <artifactId>download-maven-plugin</artifactId>
            <version>1.13.0</version>
            <executions>
              <execution>
                <id>fetch-wallet-account-spec</id>
                <phase>generate-resources</phase>
                <goals><goal>wget</goal></goals>
                <configuration>
                  <url>https://raw.githubusercontent.com/${wallet-account-spec.repo}/${wallet-account-spec.ref}/${wallet-account-spec.path}</url>
                  <outputDirectory>${project.basedir}/src/main/resources/external-apispec</outputDirectory>
                  <outputFileName>wallet-account-openapi-v0.yaml</outputFileName>
                  <overwrite>true</overwrite>
                </configuration>
              </execution>
              <execution>
                <id>fetch-wallet-account-origin-spec</id>
                <phase>generate-resources</phase>
                <goals><goal>wget</goal></goals>
                <configuration>
                  <url>https://raw.githubusercontent.com/${wallet-account-spec.repo}/${wallet-account-spec.ref}/${wallet-account-origin-spec.path}</url>
                  <outputDirectory>${project.basedir}/src/main/resources/external-apispec</outputDirectory>
                  <outputFileName>wallet-account-openapi-origin.yaml</outputFileName>
                  <overwrite>true</overwrite>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

  <build>
    <finalName>wallet-client-gateway-ci-test</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>org.springframework.boot</groupId>
              <artifactId>spring-boot-configuration-processor</artifactId>
            </path>
            <path>
              <groupId>io.soabase.record-builder</groupId>
              <artifactId>record-builder-processor</artifactId>
              <version>${record-builder.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.6.0</version>
      </plugin>

      <!-- JaCoCo plugin -->
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>${jacoco-maven-plugin.version}</version>
        <configuration>
          <excludes>
            <exclude>se/digg/wallet/gateway/api/v0/**</exclude>
            <exclude>se/digg/wallet/gateway/client/account/v0/**</exclude>
            <exclude>se/digg/wallet/gateway/client/hsm/v1/**</exclude>
            <exclude>se/digg/wallet/gateway/client/provider/v0/**</exclude>
            <exclude>**/*Builder.class</exclude>
            <exclude>**/*Builder$*.class</exclude>
          </excludes>
        </configuration>
        <executions>
          <execution>
            <id>prepare-agent</id>
            <goals><goal>prepare-agent</goal></goals>
          </execution>
          <execution>
            <id>report</id>
            <phase>test</phase>
            <goals><goal>report</goal></goals>
          </execution>
        </executions>
      </plugin>



      <!-- Formatter plugin -->
      <plugin>
        <groupId>net.revelc.code.formatter</groupId>
        <artifactId>formatter-maven-plugin</artifactId>
        <version>${formatter-maven-plugin.version}</version>
        <configuration>
          <configFile>
            ${project.basedir}/development/format/eclipse-java-google-style.xml
          </configFile>
          <lineEnding>LF</lineEnding>
          <compilerSource>${maven.compiler.source}</compilerSource>
          <compilerCompliance>${maven.compiler.source}</compilerCompliance>
          <compilerTargetPlatform>
            ${maven.compiler.target}
          </compilerTargetPlatform>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>validate</goal>
            </goals>
            <phase>verify</phase>
          </execution>
        </executions>
      </plugin>

      <!-- Checkstyle plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>${maven-checkstyle-plugin.version}</version>
        <dependencies>
          <dependency>
            <groupId>com.puppycrawl.tools</groupId>
            <artifactId>checkstyle</artifactId>
            <version>${checkstyle.version}</version>
          </dependency>
        </dependencies>
        <configuration>
          <configLocation>
            ${project.basedir}/development/lint/google_checks.xml
          </configLocation>
          <consoleOutput>true</consoleOutput>
          <failsOnError>true</failsOnError>
          <linkXRef>false</linkXRef>
        </configuration>
        <executions>
          <execution>
            <id>validate</id>
            <phase>validate</phase>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- PMD plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-pmd-plugin</artifactId>
        <version>${maven-pmd-plugin.version}</version>
        <configuration>
          <rulesets>
            <ruleset>${project.basedir}/development/sast/pmd_default_java.xml</ruleset>
          </rulesets>
          <failOnViolation>true</failOnViolation>
          <printFailingErrors>true</printFailingErrors>
          <linkXRef>false</linkXRef>
        </configuration>
      </plugin>

      <!-- SpotBugs plugin -->
      <plugin>
        <groupId>com.github.spotbugs</groupId>
        <artifactId>spotbugs-maven-plugin</artifactId>
        <version>${spotbugs-maven-plugin.version}</version>
        <configuration>
          <effort>Max</effort>
          <threshold>Low</threshold>
          <failOnError>true</failOnError>
          <excludeFilterFile>development/spotbugs-exclude.xml</excludeFilterFile>
        </configuration>
      </plugin>

      <!-- OpenAPI Generator plugin -->
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>${openapi-generator-maven-plugin.version}</version>
        <executions>
          <execution>
            <id>wallet-client-gateway-openapi-v0</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>
                ${project.basedir}/src/main/resources/static/wallet-client-gateway-openapi-v0.yaml
              </inputSpec>
              <generatorName>spring</generatorName>
              <apiPackage>se.digg.wallet.gateway.api.v0</apiPackage>
              <modelPackage>se.digg.wallet.gateway.api.v0.model</modelPackage>
              <generateSupportingFiles>false</generateSupportingFiles>
              <generateApiTests>true</generateApiTests>
              <configOptions>
                <useSpringBoot4>true</useSpringBoot4>
                <interfaceOnly>true</interfaceOnly>
                <useTags>true</useTags>
                <skipDefaultInterface>true</skipDefaultInterface>
                <generateBuilders>true</generateBuilders>
                <useOptional>true</useOptional>
                <includeHttpRequestContext>false</includeHttpRequestContext>
                <implicitHeadersRegex>^(Wallet-Device-OS|Wallet-Device-OS-Version|Wallet-Device-Model|Wallet-App-Version)$</implicitHeadersRegex>
              </configOptions>
            </configuration>
          </execution>
          <execution>
            <id>wallet-accouint-api-client-v0</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>
                ${project.basedir}/src/main/resources/external-apispec/wallet-account-openapi-v0.yaml
              </inputSpec>
              <generatorName>java</generatorName>
              <configOptions>
                <apiPackage>se.digg.wallet.gateway.client.account.v0.api</apiPackage>
                <modelPackage>se.digg.wallet.gateway.client.account.v0.model</modelPackage>
                <generateBuilders>true</generateBuilders>
                <library>restclient</library>
                <useSpringBoot4>true</useSpringBoot4>
                <useJackson3>true</useJackson3>
                <useJakartaEe>true</useJakartaEe>
              </configOptions>
            </configuration>
          </execution>
          <execution>
            <id>wallet-r2ps-hsm-api-client-v0</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <skipValidateSpec>true</skipValidateSpec>
              <inputSpec>
                ${project.basedir}/src/main/resources/external-apispec/wallet-hsm-openapi-v1.json
              </inputSpec>
              <generatorName>java</generatorName>
              <configOptions>
                <apiPackage>se.digg.wallet.gateway.client.hsm.v1.api</apiPackage>
                <modelPackage>se.digg.wallet.gateway.client.hsm.v1.model</modelPackage>
                <generateBuilders>true</generateBuilders>
                <library>restclient</library>
                <useSpringBoot4>true</useSpringBoot4>
                <useJackson3>true</useJackson3>
                <useJakartaEe>true</useJakartaEe>
              </configOptions>
            </configuration>
          </execution>
          <execution>
            <id>wallet-provider-api-client-v0</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>
                ${project.basedir}/src/main/resources/external-apispec/wallet-provider-openapi-v0.yaml
              </inputSpec>
              <generatorName>java</generatorName>
              <configOptions>
                <apiPackage>se.digg.wallet.gateway.client.provider.v0.api</apiPackage>
                <modelPackage>se.digg.wallet.gateway.client.provider.v0.model</modelPackage>
                <generateBuilders>true</generateBuilders>
                <library>restclient</library>
                <useSpringBoot4>true</useSpringBoot4>
                <useJackson3>true</useJackson3>
                <useJakartaEe>true</useJakartaEe>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- Build Helper plugin -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>${build-helper-maven-plugin.version}</version>
        <executions>
          <execution>
            <id>add-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.basedir}/target/generated-sources/openapi/src/main/java</source>
              </sources>
            </configuration>
          </execution>
          <execution>
            <id>add-test-source</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>add-test-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.basedir}/target/generated-sources/openapi/src/test/java</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.openapitools.openapidiff</groupId>
        <artifactId>openapi-diff-maven</artifactId>
        <version>${openapi-diff-maven.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>diff</goal>
            </goals>
            <configuration>
              <oldSpec>https://wallet.sandbox.digg.se/api/wallet-client-gateway-openapi-v0.yaml</oldSpec>
              <newSpec>${project.basedir}/target/classes/static/wallet-client-gateway-openapi-v0.yaml</newSpec>
              <failOnIncompatible>false</failOnIncompatible>
              <failOnChanged>false</failOnChanged>
              <consoleOutputFileName>${project.basedir}/target/openapi-diff.txt</consoleOutputFileName>
              <jsonOutputFileName>${project.basedir}/target/openapi-diff.json</jsonOutputFileName>
              <markdownOutputFileName>${project.basedir}/target/openapi-diff.md</markdownOutputFileName>
            </configuration>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>
</project>
