# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
# SPDX-License-Identifier: EUPL-1.2

services:
  valkey:
    image: valkey/valkey:9.1.1@sha256:64e361b630ecf18dff7ca4df6a88e6eafc193687eb48cff2c7e0a293ab67d29a
    ports:
      - "6379:6379"
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge
